# Generated by Django 6.0.7 on 2026-09-05 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0013_device_enable_secret'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Execution'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('generated_commands', models.TextField(blank=True, default='')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('action_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_requests', to='actions.actiondefinition')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_requests', to='devices.device')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ActionParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('data_type', models.CharField(choices=[('STRING', 'String'), ('INTEGER', 'Integer'), ('IP_ADDRESS', 'IP Address'), ('BOOLEAN', 'Boolean')], default='STRING', max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('default_value', models.CharField(blank=True, default='', max_length=255)),
                ('validation_regex', models.CharField(blank=True, default='', max_length=255)),
                ('action_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='actions.actiondefinition')),
            ],
            options={
                'unique_together': {('action_definition', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ActionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(max_length=50)),
                ('template_text', models.TextField()),
                ('action_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='actions.actiondefinition')),
            ],
            options={
                'unique_together': {('action_definition', 'device_type')},
            },
        ),
        migrations.CreateModel(
            name='DevicePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('action_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_permissions', to='actions.actiondefinition')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_permissions', to='devices.device')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'device', 'action_definition')},
            },
        ),
    ]
