# Generated by Django 6.0.7 on 2026-07-19 23:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diff_text', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('FLAGGED', 'Flagged'), ('ACKNOWLEDGED', 'Acknowledged')], default='FLAGGED', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('hostname', models.CharField(max_length=255, unique=True)),
                ('management_ip', models.GenericIPAddressField(protocol='IPv4', unique=True)),
                ('port', models.IntegerField(default=22, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('device_type', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('poll_interval_minutes', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)])),
                ('alert_threshold', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered', models.BooleanField(default=False)),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='devices.configchange')),
            ],
        ),
        migrations.AddField(
            model_name='configchange',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='devices.device'),
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('raw_text', models.TextField()),
                ('config_hash', models.CharField(max_length=64)),
                ('is_baseline', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='devices.device')),
            ],
        ),
        migrations.AddField(
            model_name='configchange',
            name='new_snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='devices.snapshot'),
        ),
        migrations.AddField(
            model_name='configchange',
            name='old_snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='devices.snapshot'),
        ),
    ]
