# Generated by Django 6.0.7 on 2026-07-20 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_poll_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='device',
            name='last_poll_status',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('ERROR', 'Error')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='last_polled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configchange',
            name='status',
            field=models.CharField(choices=[('FLAGGED', 'Flagged'), ('ACKNOWLEDGED', 'Acknowledged'), ('SUPERSEDED', 'Superseded')], default='FLAGGED', max_length=15),
        ),
    ]
