# Generated by Django 6.0.7 on 2026-07-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_last_poll_error_device_last_poll_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_poll_duration_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configchange',
            name='status',
            field=models.CharField(choices=[('FLAGGED', 'Flagged'), ('ACKNOWLEDGED', 'Acknowledged')], default='FLAGGED', max_length=15),
        ),
    ]
