# Generated by Django 6.0.7 on 2026-07-21 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_last_poll_duration_ms_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='configchange',
            options={'ordering': ['-detected_at']},
        ),
        migrations.AlterModelOptions(
            name='snapshot',
            options={'ordering': ['-taken_at']},
        ),
    ]
