# Generated by Django 6.0.7 on 2026-08-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_alter_alert_options_alter_configchange_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configchange',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configchange',
            name='status',
            field=models.CharField(choices=[('FLAGGED', 'Flagged'), ('ACKNOWLEDGED', 'Acknowledged'), ('INFORMATIONAL', 'Informational')], default='FLAGGED', max_length=15),
        ),
    ]
