# Generated by Django 6.0.7 on 2026-08-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_configchange_acknowledged_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
