# Generated by Django 6.0.7 on 2026-08-15 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_device_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeverityClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('rank', models.IntegerField(unique=True)),
            ],
            options={
                'ordering': ['-rank'],
            },
        ),
        migrations.RemoveField(
            model_name='configchange',
            name='severity',
        ),
        migrations.RemoveField(
            model_name='device',
            name='alert_threshold',
        ),
        migrations.AddField(
            model_name='device',
            name='detection_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='devices.detectionprofile'),
        ),
        migrations.AddField(
            model_name='configchange',
            name='severity_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes', to='devices.severityclass'),
        ),
        migrations.CreateModel(
            name='TrackedConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('pattern', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('BUILTIN', 'Built-in'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('severity_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='concepts', to='devices.severityclass')),
            ],
        ),
        migrations.AddField(
            model_name='detectionprofile',
            name='tracked_concepts',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='devices.trackedconcept'),
        ),
        migrations.AddField(
            model_name='configchange',
            name='matched_concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_changes', to='devices.trackedconcept'),
        ),
    ]
