# Generated by Django 6.0.7 on 2026-08-15 06:06
from django.db import migrations

BUILTIN_CONCEPTS = [
    # (name, description, pattern, severity_rank_name)
    ("ACL Change", "An access-list was added, removed, or modified.", r"access-list|no ip access-list", "High"),
    ("Routing Protocol Disabled", "A routing protocol (e.g. OSPF, BGP) was removed.", r"no router (ospf|bgp|eigrp|rip)", "High"),
    ("Interface Shutdown", "An interface was administratively shut down.", r"^\+.*\bshutdown\b", "High"),
    ("HSRP Change", "HSRP/VRRP standby group configuration changed.", r"standby \d+ (priority|ip|preempt)", "Medium"),
    ("VLAN Change", "A VLAN was added, removed, or modified.", r"vlan \d+", "Medium"),
    ("Static Route Change", "A static route was added or removed.", r"ip route", "Medium"),
    ("Interface IP Change", "An interface's IP address was changed.", r"ip address \d+\.\d+\.\d+\.\d+", "Medium"),
    ("OSPF Area Change", "An OSPF area/network statement changed.", r"router ospf|network .* area", "Medium"),
    ("BGP Neighbor Change", "A BGP neighbor statement changed.", r"neighbor \d+\.\d+\.\d+\.\d+", "Medium"),
    ("NAT Rule Change", "A NAT rule was added or removed.", r"ip nat (inside|outside)", "Medium"),
    ("DHCP Pool Change", "A DHCP pool configuration changed.", r"ip dhcp pool", "Medium"),
    ("SNMP Community Change", "An SNMP community string was added or changed.", r"snmp-server community", "Medium"),
    ("NTP Server Change", "The NTP server configuration changed.", r"ntp server", "Low"),
    ("Logging Change", "Syslog/logging configuration changed.", r"logging (host|trap|buffered)", "Low"),
    ("Description Change", "An interface or line description changed.", r"description", "Low"),
    ("Banner Change", "The login/MOTD banner changed.", r"banner", "Low"),
    ("Hostname Change", "The device hostname changed.", r"^\+hostname|^-hostname", "Medium"),
    ("Domain Name Change", "The device domain name changed.", r"domainname", "Low"),
    ("Line/VTY Change", "Console or VTY line configuration changed.", r"line (con|vty)", "Low"),
    ("Spanning Tree Change", "Spanning-tree configuration changed.", r"spanning-tree", "Medium"),
]


def seed_data(apps, schema_editor):
    SeverityClass = apps.get_model("devices", "SeverityClass")
    TrackedConcept = apps.get_model("devices", "TrackedConcept")

    low, _ = SeverityClass.objects.get_or_create(name="Low", defaults={"rank": 10})
    medium, _ = SeverityClass.objects.get_or_create(name="Medium", defaults={"rank": 20})
    high, _ = SeverityClass.objects.get_or_create(name="High", defaults={"rank": 30})

    rank_map = {"Low": low, "Medium": medium, "High": high}

    for name, description, pattern, severity_name in BUILTIN_CONCEPTS:
        TrackedConcept.objects.get_or_create(
            name=name,
            defaults={
                "description": description,
                "pattern": pattern,
                "severity_class": rank_map[severity_name],
                "source": "BUILTIN",
            },
        )


def reverse_seed(apps, schema_editor):
    SeverityClass = apps.get_model("devices", "SeverityClass")
    TrackedConcept = apps.get_model("devices", "TrackedConcept")
    TrackedConcept.objects.filter(source="BUILTIN").delete()
    SeverityClass.objects.filter(name__in=["Low", "Medium", "High"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0007_detectionprofile_severityclass_and_more"),  # ← set this to the actual previous migration filename
    ]

    operations = [
        migrations.RunPython(seed_data, reverse_seed),
    ]
