# Generated by Django 6.0.7 on 2026-08-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_seed_severity_and_concepts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configchange',
            name='matched_concept',
        ),
        migrations.AddField(
            model_name='configchange',
            name='matched_concepts',
            field=models.ManyToManyField(blank=True, related_name='matched_changes', to='devices.trackedconcept'),
        ),
    ]
