# Generated by Django 6.0.7 on 2026-08-17 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_configchange_acknowledged_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='consecutive_failures',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
