# Generated by Django 6.0.7 on 2026-09-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0012_fix_concept_patterns'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='enable_secret',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
