# Generated by Django 6.0.7 on 2026-09-10 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_seed_builtin_actions'),
        ('devices', '0013_device_enable_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='configchange',
            name='change_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resulting_config_changes', to='actions.changerequest'),
        ),
    ]
